# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.IntegerField(default=1),
        ),
    ]
