# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_auto_20170807_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
