# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0003_personalinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('preContent', models.CharField(max_length=100)),
                ('nextContent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.User')),
            ],
        ),
    ]
