# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0005_auto_20170819_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='address',
            field=models.FileField(upload_to='contens/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='nextContent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextcontent', to='toolbox.Content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='preContent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precontent', to='toolbox.Content'),
        ),
    ]
