# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0006_auto_20170819_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='nextContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextcontent', to='toolbox.Content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='preContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precontent', to='toolbox.Content'),
        ),
    ]
