# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0007_auto_20170825_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='address',
            field=models.FileField(upload_to='contents/'),
        ),
    ]
