# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0009_auto_20170829_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tag',
            field=models.CharField(choices=[('Images', 'Images'), ('Formulas', 'Formulas'), ('Activities', 'Activities'), ('Skills', 'Skills'), ('Social frameworks', 'Social frameworks'), ('Concepts', 'Concepts'), ('Myths & notions', 'Myths & notions'), ('Principles', 'Principles')], max_length=30),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('doc', 'doc'), ('pdf', 'pdf'), ('image', 'image'), ('vodeo', 'video'), ('audio', 'audio'), ('other', 'other')], max_length=30),
        ),
    ]
