# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0010_auto_20170905_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentName', models.CharField(max_length=100)),
                ('profileName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('doc', 'doc'), ('pdf', 'pdf'), ('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('other', 'other')], max_length=30),
        ),
    ]
