# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0012_auto_20170905_0223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('profileName',)},
        ),
    ]
