# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0013_auto_20170905_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='profileText',
            field=models.TextField(default='', max_length=100),
        ),
    ]
