# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0014_content_profiletext'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='note',
            field=models.CharField(default='', max_length=300),
        ),
    ]
