# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0015_personalinfo_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.Content')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.Program')),
            ],
        ),
        migrations.DeleteModel(
            name='profileRelation',
        ),
    ]
