# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0016_auto_20170912_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='contentsNumber',
            field=models.IntegerField(default=0),
        ),
    ]
