# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 06:23
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0019_auto_20171003_0605'),
    ]



