# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0021_auto_20171003_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='nation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='profile',
            field=models.ManyToManyField(to='toolbox.Profile'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='programs',
            field=models.ManyToManyField(to='toolbox.Program'),
        ),
        migrations.AlterField(
            model_name='content',
            name='focus',
            field=models.CharField(choices=[('Emotional Intelligence', 'Emotional Intelligence'), ('Social Intelligence', 'Social Intelligence'), ('Self Actualization', 'Self Actualization')], default='Emotional Intelligence', max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
