# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0022_auto_20171125_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='toolbox.Category'),
        ),
    ]
