# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0023_auto_20171209_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
