# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0025_auto_20171209_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='toolbox.Category'),
        ),
        migrations.AddField(
            model_name='content',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
