# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0028_contentcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='toolbox.ContentCategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
