# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0029_auto_20171222_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='toolbox.ContentCategory'),
        ),
    ]
