# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0030_auto_20171222_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='contents/categories/'),
        ),
    ]
