# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0031_contentcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcategory',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='categories/'),
        ),
    ]
