# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0032_auto_20180102_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcategory',
            name='image',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories/'),
        ),
    ]
