# Generated by Django 2.0.1 on 2018-01-14 07:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0033_auto_20180102_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='toolbox.ContentCategory'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.User'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.Content'),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.Program'),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='toolbox.User'),
        ),
    ]
