# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0034_auto_20180114_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('plan_acuity_package_link', models.URLField(blank=True, default='')),
                ('plan_acuity_appointment_id', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='toolbox_certificate_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='toolbox_user_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='address',
            field=models.FileField(upload_to='./'),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='./'),
        ),
    ]
