# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0035_auto_20180128_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.User'),
        ),
    ]
