# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0036_auto_20180129_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='address',
            field=models.FileField(upload_to='contents'),
        ),
    ]
