# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0037_auto_20180202_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdetail',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
