# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0038_auto_20180203_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='address',
            field=models.FileField(upload_to='./'),
        ),
    ]
