# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0039_auto_20180203_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_id',
            field=models.IntegerField(default=0),
        ),
    ]
