#class Constants:
AUTH_KEY = "Basic MTQ5MDczMzM6Y2MwNWM0NzQwZTQ5N2UxNzZmNzM4ZmRhM2Y5MmY2ZDY="
HEADERS = {"Authorization":AUTH_KEY}

ACUITY_HOST_URL = "https://acuityscheduling.com/api/v1/"
ACUITY_CERTIFICATES_CHECK = ACUITY_HOST_URL+"certificates/check"
ACUITY_CHECK_AVAILABLE_TIME = ACUITY_HOST_URL+"availability/times"
ACUITY_POST_SCHEDULE = ACUITY_HOST_URL+"appointments"

PLAN_1 = 5214156
PLAN_2 = 5214183
PLAN_3 = 5214183
TOOLBOX_INDIVIDUALIZED_PLAN = 5214156